<a href="https://colab.research.google.com/github/jagath806/learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [4]:
#please provide your answer below this line.
 
import numpy as np
x=np.arange(0,9).reshape(3,3)
y=np.arange(1,10).reshape(3,3)
print(x)
print(y)
z=x.dot(y)
print(z)
print(z.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[[ 18  54  90]
 [ 21  66 111]
 [ 24  78 132]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [3]:
#please provide your answer below this line.
 
import numpy as np
x=np.array([(55,25,15),(30,44,2),(11,45,77)])
print(x)
print(np.linalg.det(x))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180.0000000001
