<a href="https://colab.research.google.com/github/jagath806/learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
import numpy as np
x=np.random.random((3,3))
print(x)

[[0.57954923 0.02594704 0.7926601 ]
 [0.84749679 0.03803344 0.88823248]
 [0.59171791 0.29590604 0.27189294]]


2. Generate two 4 x 4 matrix using numpy and 
 
 a) Reshape it to 2 x 8matrix and vertically stack it.
 
 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [ ]:
#please provide your answer below this line.
import numpy as np
x=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
y=np.array([(2,4,6,8),(5,10,15,20),(3,6,9,12),(1,3,5,7)])
print(x)
print(y)
c=x.reshape(2,8)
d=y.reshape(2,8)
print(c)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4  6  8]
 [ 5 10 15 20]
 [ 3  6  9 12]
 [ 1  3  5  7]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 2  4  6  8  5 10 15 20]
 [ 3  6  9 12  1  3  5  7]]


In [ ]:
np.vstack((c,d))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 2,  4,  6,  8,  5, 10, 15, 20],
       [ 3,  6,  9, 12,  1,  3,  5,  7]])

In [ ]:
 np.hstack((c,d))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  2,  4,  6,  8,  5, 10, 15, 20],
       [ 9, 10, 11, 12, 13, 14, 15, 16,  3,  6,  9, 12,  1,  3,  5,  7]])